# Generated by Django 6.0 on 2025-12-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fuelstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'fuel_stations',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuel_statio_latitud_c84538_idx'), models.Index(fields=['state'], name='fuel_statio_state_db56e5_idx'), models.Index(fields=['retail_price'], name='fuel_statio_retail__463e8c_idx')],
            },
        ),
    ]
